colnames(SessionsPerDay)<-c("doy","sessions")
SessionsPerDay$doy<-yday(SessionsPerDay$doy) # use first time
plot(sessions~doy, data = SessionsPerDay, xlab = "doy")
title(main="SessionsPerDay")
lm<-lm(sessions~doy, data = SessionsPerDay)
summary(lm)
abline(lm, col="pink")
new<-data.frame((doy=seq(0,365,1)))
p2<-predict(lm,newdata = new,interval="confidence",level=0.95)
lines(new$X.doy...seq.0..365..1..,p2[,1],col="blue")
lines(new$X.doy...seq.0..365..1..,p2[,2],col="blue")
lines(new$X.doy...seq.0..365..1..,p2[,3],col="blue")
p3<-predict(lm,newdata = new,interval="prediction",level=0.95)
lines(new$X.doy...seq.0..365..1..,p2[,2],col="green",lty=2)
lines(new$X.doy...seq.0..365..1..,p2[,3],col="green",lty=2)